<a href="https://colab.research.google.com/github/nitin-barthwal/pytorch/blob/master/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

In [3]:
torch.zeros(5,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
x = torch.tensor([5.5,3,4,55])
x

tensor([ 5.5000,  3.0000,  4.0000, 55.0000])

In [5]:
y = x.new_ones(5,3,dtype=torch.int)
y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [6]:
z = x.new_full((5,3),9)
z

tensor([[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]])

In [7]:
torch.add(y,z)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])

In [8]:
torch.empty(5,3,dtype=torch.long)

tensor([[           81078784,        206158430258,        206158430253],
        [       193273528374,        223338299440,        210453397588],
        [       249108103220,        244813135925,        227633266746],
        [       197568495673,        223338299448,        227633266742],
        [       219043332147, 4621819117588971610, 4621819117588971520]])

In [9]:
c = torch.randn(3,3)
c

tensor([[ 0.5651, -0.3192, -0.9892],
        [-0.7198,  0.6928,  0.6474],
        [-0.0174, -0.0534, -1.2811]])

In [10]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243


In [11]:
c.transpose(0, 1)

tensor([[ 0.5651, -0.7198, -0.0174],
        [-0.3192,  0.6928, -0.0534],
        [-0.9892,  0.6474, -1.2811]])

Construct a 5x3 matrix, uninitialized:



In [12]:
x = torch.empty(5, 3)
if torch.cuda.is_available():
  device = torch.device("cuda")
  q=torch.randn(5,3,device=device)
  p = y.to(device)
  print(q+p)
else:
  print('No')

tensor([[ 0.2476, -0.4470,  1.3889],
        [ 1.3118,  0.2874,  2.3985],
        [-0.4652,  1.2352,  0.7945],
        [ 1.4363,  1.3915,  1.5313],
        [ 1.3968, -1.2784,  1.3364]], device='cuda:0')


In [13]:
import time
import numpy as np
stime2 = time.time()

d = 3000 
A= np.random.rand(d,d)
B=np.random.rand(d,d)
c= np.dot(A,B)
print('Time taken = ' ,time.time() - stime2)

Time taken =  1.5328524112701416


In [14]:
stime2 = time.time()

d = 3000 
J= torch.rand(d,d)
K=torch.rand(d,d)
c= torch.mm(J,K)
print('Time taken = ' ,time.time() - stime2)

Time taken =  0.654888391494751


In [19]:
stime2 = time.time()

d = 3000 
J= torch.rand(d,d, device=device)
K=torch.rand(d,d,device = device)
c= torch.mm(J,K)
print('Time taken = ' ,time.time() - stime2)

Time taken =  0.0007901191711425781


Construct a randomly initialized matrix:



In [0]:
x = torch.rand(5, 3)
print(x)

Construct a matrix filled zeros and of dtype long:



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

Construct a tensor directly from data:



In [0]:
x = torch.tensor([5.5, 3])
print(x)

or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

Get its size:



In [0]:
print(x.size())

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [0]:
y = torch.rand(5, 3)
print(x + y)

Addition: syntax 2



In [0]:
print(torch.add(x, y))

Addition: providing an output tensor as argument



In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

Addition: in-place



In [0]:
# adds x to y
y.add_(x)
print(y)

<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [0]:
print(x[:, 1])

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [0]:
x = torch.randn(1)
print(x)
print(x.item())

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [0]:
a = torch.ones(5)
print(a)

In [0]:
b = a.numpy()
print(b)

See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!